[package]
name = "tui-savers-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27"
derive_builder = "0.12"
once_cell = "1.18"
pico-args = "0.5"
rand = "0.8.5"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "rain_benchmarks"
harness = false

# optimized to size
[profile.release]
panic = "abort"
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true  # enable link time optimization
codegen-units = 1
