[package]
name = "matrix-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
log = "0.4.17"
ndarray = { version = "0.15.6", features = ["rayon"] }
once_cell = "1.16.0"
pico-args = "0.5.0"
rand = "0.8.5"
rayon = "1.6.0"
simple_logger = "4.0.0"

# old optimization
# [profile.release]
# strip = true
# opt-level = "z"
# lto = true
# codegen-units = 1
# panic = "abort"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"

