[package]
name = "tui-savers-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
derive_builder = "0.12.0"
log = "0.4.17"
once_cell = "1.16.0"
pico-args = "0.5.0"
rand = "0.8.5"
simple_logger = "4.0.0"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "rain_benchmarks"
harness = false

[profile.release]
opt-level = "z"
codegen-units = 1
lto = "fat"
panic = "abort"

