name: Check Nix Formatting/Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  nix-fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Check formatting
        run: nix fmt -- --fail-on-change
  nix-build:
    name: Nix Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Build with nix
        run: nix build
